#!/usr/bin/env python

import roslib
roslib.load_manifest('tfx')
import rospy
import tf

from tfx.adjustable_static_pub import *

if __name__ == '__main__':
	rospy.init_node('static_tf',anonymous=True)
	listener = tf.TransformListener()

	adj = AdjustableStaticPublisher(listener,'tf')

	adj.run()